=== KaietdePablo/DTD_III/DTD_III/cuento.dtd
<!ELEMENT cuento (personajes, trama, (etiqueta)*, (precio)?)>
<!ATTLIST cuento
    cod CDATA #REQUIRED
    titulo CDATA #REQUIRED
    genero (infantil | fantasia | terror) #IMPLIED
>

<!ELEMENT personajes (personaje+)>
<!ELEMENT personaje (nombre, genero, (descripcion | descripcion_fisica | imagen | url)*)>
<!ATTLIST personaje
    id CDATA #REQUIRED
    tipo (principal | secundario | antagonista) "principal"
    genero (M | F | N) #REQUIRED
>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT descripcion_fisica (#PCDATA)>


<!ELEMENT trama (#PCDATA)>
<!ELEMENT etiqueta EMPTY>
<!ATTLIST etiqueta
    nombre CDATA #REQUIRED
>

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio
    moneda CDATA "eur"
>

=== KaietdePablo/DTD_III/DTD_III/cuento1.xml
<!-- 
Nombre: Kaiet de Pablo
Curso: ASIR
Fecha: 03/04/2025
Ejercicio: Cuento 1
-->
<!DOCTYPE cuento SYSTEM "cuento.dtd">
<cuento cod="01" titulo="El Bosque Encantado" genero="infantil">
    <personajes>
        <personaje id="1" tipo="principal" genero="M">
            <nombre>pepe</nombre>
            <descripcion>un chico guerrero</descripcion>
            <descripcion_fisica> Pelo corto, ojos azules</descripcion_fisica>
        </personaje>
        <personaje id="2" tipo="secundario" genero="F">
            <nombre>maria</nombre>
            <descripcion>Una ni√±a curiosa</descripcion>
        </personaje>
    </personajes>
    <trama>pepe y maria entran en un bosque misterioso lleno de magia...</trama>
    <etiqueta nombre="aventura"/>
    <etiqueta nombre="amistad"/>
    <precio moneda="eur">12.99</precio>
</cuento>

=== KaietdePablo/DTD_III/DTD_III/cuento2.xml
<!-- 
Nombre: Kaiet de Pablo
Curso: ASIR
Fecha: 03/04/2025
Ejercicio: Cuento 2
-->
<!DOCTYPE cuento SYSTEM "cuento.dtd">
<cuento cod="02" titulo="La Maldición del Bosque" genero="terror">
    <personajes>
        <personaje id="3" tipo="principal" genero="M">
            <nombre>Raúl</nombre>
            <descripcion>Un joven investigador del ocultismo</descripcion>
        </personaje>
        <personaje id="4" tipo="antagonista" genero="N">
            <nombre>La Sombra</nombre>
            <descripcion>Una entidad maligna que se alimenta del miedo</descripcion>
        </personaje>
    </personajes>
    <trama>Raúl se aventura en un bosque antiguo donde la sombra de un antiguo hechizo sigue acechando, buscando almas para consumir...</trama>
    <etiqueta nombre="terror"/>
    <precio>14.99</precio>
</cuento>
